# Holds username and password for the MongoDB application.
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  # Note: Values in secrets are base64 encoded. So, we cannot store them in plain text.
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==